# Generated by Django 5.1.4 on 2024-12-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='email',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='first_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='last_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
